### ISSUE TITLE
Cannot find story matching '' after HMR.

### ISSUE THREAD

**Issue by Lurtroxx** [leotm/react-native-template-new-architecture#1318]
Followed setup and app runs fine on normal <App /> component, and <StorybookUI /> component from index. After creating a filestructure as follows, the same error appears on yarn get-storybook. 

<img width="253" alt="image" src="https://user-images.githubusercontent.com/32040179/209038770-429e557a-a22c-40a0-9c8b-43d2ff39cca2.png">

![image](https://user-images.githubusercontent.com/32040179/209038604-c5d463bc-5acc-4713-acc9-e5e9281576b5.png)

Any suggestions?

**Comment by Lurtroxx** [comment]
The getStories function populates the array. I dont know what else to do really in order to get it working. Have been grasping at straws. 
<img width="624" alt="image" src="https://user-images.githubusercontent.com/32040179/209038969-8278d59e-d975-4bc0-b3b5-694bf8da037a.png">

**Comment by Lurtroxx** [comment]
Resolved.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/32040179/209047816-46f8928f-a736-453b-9ce3-4f8401679422.png">

**Comment by leotm** [comment]
glad you figured it out, feel free to try some [examples](https://github.com/storybookjs/react-native/tree/next-6.0/examples/native/components) too which should look something like this

<img width="1440" alt="Screenshot 2022-12-19 at 15 41 36" src="https://user-images.githubusercontent.com/1881059/209166762-6bcfd19f-3796-46c9-9612-b4eeedf8443a.png">

and give me or @dannyhw a shout if any trouble
