### ISSUE TITLE
storybook server issue?

### ISSUE THREAD

**Issue by nicolasburtey** [leotm/react-native-template-new-architecture#1508]
trying to test storybook from the template. I can launch the server, but the browser is empty.

error is in the screenshot, also pasted here: 

```
vendors~main.manager.bundle.js:68849 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
printWarning @ vendors~main.manager.bundle.js:68849
DevTools failed to load source map: Could not load content for http://localhost:7007/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/11156370/219378081-8067eaf1-b2e9-4c43-8e63-f59fe3e98349.png">

note: I can launch storybook in the mobile app just fine. just the browser seems to have issue.

**Comment by leotm** [comment]
gotcha sry i think its this i missed in the ReadMe

https://github.com/leotm/react-native-template-new-architecture/blob/22776eda1daa6e23edff224aaeba53cc8717cb21/package.json#L27

does that work

**Comment by leotm** [comment]
otherwise the setup looks correct w sockets enabled

https://github.com/leotm/react-native-template-new-architecture/blob/22776eda1daa6e23edff224aaeba53cc8717cb21/.storybook/Storybook.tsx#L11

**Comment by nicolasburtey** [comment]
yup this doesn't work.

maybe some relevant details:
- using mac m1/m2
- had to apply diff below for it to compile

```
diff --git a/package.json b/package.json
index a6dcab4a..8f13e533 100644
--- a/package.json
+++ b/package.json
@@ -24,7 +24,7 @@
     "snap": "jest -u",
     "get-stories": "sb-rn-get-stories --config-path=./.storybo
ok",
     "storybook-watcher": "sb-rn-watcher --config-path=./.story
book",
-    "storybook-server": "react-native-storybook-server",
+    "storybook-server": "NODE_OPTIONS=--openssl-legacy-provide
r react-native-storybook-server",
     "flipper-server": "flipper-server",
     "node-server": "ts-node node.ts",
     "deno-server": "deno run --allow-net deno.ts",
```

otherwise running into those issues:

```
% yarn storybook-server
info => Loading presets
ℹ ｢wdm｣: wait until bundle finished: 
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/n/Code/react-native-template-new-architecture/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/n/Code/react-native-template-new-architecture/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/n/Code/react-native-template-new-architecture/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/n/Code/react-native-template-new-architecture/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/n/Code/react-native-template-new-architecture/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/n/Code/react-native-template-new-architecture/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/n/Code/react-native-template-new-architecture/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/n/Code/react-native-template-new-architecture/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.0
```

**Comment by leotm** [comment]
thanks and appreciate the info ^

briefly looking further my hunch is
- https://github.com/leotm/react-native-template-new-architecture/pull/1442

created version mismatch
https://github.com/leotm/react-native-template-new-architecture/blob/0b2e0c2f6afaac98713518fce170df8793448b41/package.json#L78-L79

_nb: [@storybook/addon-ondevice-knobs](https://github.com/leotm/react-native-template-new-architecture/blob/0b2e0c2f6afaac98713518fce170df8793448b41/package.json#L71) also on `6.0.1-beta.12`_

possible cause also
- https://github.com/leotm/react-native-template-new-architecture/pull/1430

**Comment by leotm** [comment]
either way will look into upgrading relevant storybook deps to [`6.5.0-rc.1`](https://github.com/storybookjs/react-native/commit/deada392ffc817d872b9e3fd7b00cbede4334e02)+

TODO
- upgrade deps ([blame ref](https://github.com/storybookjs/react-native/blame/next-6.0/examples/native/package.json))
- _check config files_
- fine-tune @renovate-bot for storybook

**Comment by leotm** [comment]
fixed

<img width="1440" alt="Screenshot 2023-03-04 at 15 36 07" src="https://user-images.githubusercontent.com/1881059/222915077-c0492581-dfa6-4c42-8475-e432956065cd.png">

i'll add the PR

**Comment by leotm** [comment]
latest release [v6.5.0-rc.1](https://github.com/storybookjs/react-native/releases/tag/v6.5.0-rc.1) but latest tag [v6.5.0-rc.5](https://github.com/storybookjs/react-native/releases/tag/v6.5.0-rc.5) also tested working

<img width="1440" alt="Screenshot 2023-03-04 at 17 11 38" src="https://user-images.githubusercontent.com/1881059/222919460-30f3bd19-1af2-4019-bf84-86748a65f404.png">

required Cmd+D Reload after `yarn ios`
