### ISSUE TITLE
suggestion: run `yarn dedupe`

### ISSUE THREAD

**Issue by ewnu** [leotm/react-native-template-new-architecture#598]
seems to me your template doesn't dedupe at all.
it saved almost  700 megs when I ran it.

**Comment by leotm** [comment]
good spot @ewnu, deduplicating doesn't seem to be the case anymore with Zero Installs

> **Zero installs setups**: dependencies are deduped and committed directly to the repository, making builds more reproducible and avoiding version conflicts.

https://semaphoreci.com/blog/javascript-monorepos-yarn-workspaces

**Comment by leotm** [comment]
fixed in
- https://github.com/leotm/react-native-template-new-architecture/pull/600

**Comment by leotm** [comment]
and should be prevented in
- https://github.com/leotm/react-native-template-new-architecture/pull/599

after @renovate-bot runs again on this repo after retry/rebase'ing open PRs
