### ISSUE TITLE
ubuntu 22.04 NDK_PROJECT_PATH=null

### ISSUE THREAD

**Issue by eeeeeio** [leotm/react-native-template-new-architecture#738]
Android NDK: Aborting

C/C++: /data/adt/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
[CXX1405] error when building with ndkBuild using /data/rnnew/android/app/src/main/jni/Android.mk: Build command failed.
Error while executing process /data/adt/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/data/rnnew/android/app/src/main/jni/Android.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 NDK_OUT=/data/rnnew/android/app/build/intermediates/cxx/Debug/72b4v95a/obj NDK_LIBS_OUT=/data/rnnew/android/app/build/intermediates/cxx/Debug/72b4v95a/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/data/rnnew/android/app/build/generated/source PROJECT_BUILD_DIR=/data/rnnew/android/app/build REACT_ANDROID_DIR=/data/rnnew/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/data/rnnew/android/../node_modules/react-native/ReactAndroid/build NODE_MODULES_DIR=/data/rnnew/android/../node_modules APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:/data/rnnew/android/app/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /data/rnnew/android/app/build/react-ndk/exported/x86/libfb.so exists  or that its path is correct   

/data/adt/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

**Comment by leotm** [comment]
did you re-check
- https://github.com/leotm/react-native-template-new-architecture#android
- https://reactnative.dev/contributing/how-to-build-from-source#point-gradle-to-your-android-sdk

`android/local.properties` in particular (gitignored)

**Comment by leotm** [comment]
also do you get the same in a fresh `npx react-native init RN0691` (will bump .69.0 -> .69.1 later)

**Comment by leotm** [comment]
CI passing and `git clean -fdx` followed by the Android instructions working locally

feel free to reopen if can't reproduce in `npx react-native init FreshProject` but still happening here after re-checking the above
